android: Set export flag of .debug.MainActivity true.
Officially app entry point activity is `.MainActivity`. But with the
hack (see previous commit) we are launching `.debug.MainActivity`
which is by default not accessible by external agents to use. By
default only official entry activity is exported. So it was throwing
permission denial exception:

```

java.lang.SecurityException: Permission Denial: starting Intent {
flg=0x10000000 cmp=com.zulipmobile.debug/.MainActivity } from null
(pid=25117, uid=2000) not exported from uid 10080

```

So set export flag 'true' to launch (hacky) mainactivity by JVM.

reference:
https://stackoverflow.com/a/19829733/5612089
https://developer.android.com/guide/topics/manifest/activity-element#exported