FetchError: Show a specific message if the error is a `TimeoutError`.
And add that message and the existing message to messages_en.json;
looks like we forgot to add the existing one.